CREATE SCHEMA IF NOT EXISTS EMS;
SET SCHEMA EMS;

CREATE TABLE IF NOT EXISTS employee
(
    ID            BIGINT AUTO_INCREMENT NOT NULL,
    first_name    VARCHAR(255)    NOT NULL,
    last_name       VARCHAR(55)            NOT NULL,
    email          VARCHAR(255)    UNIQUE       NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS emp_user_role
(
    ID            BIGINT AUTO_INCREMENT NOT NULL,
    emp_user_id    BIGINT    NOT NULL,
    emp_role_id       BIGINT            NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS user
(
    ID            BIGINT AUTO_INCREMENT NOT NULL,
    first_name    VARCHAR(255)    NOT NULL,
    last_name       VARCHAR(55)            NOT NULL,
    email          VARCHAR(255)    UNIQUE       NOT NULL,
    password          VARCHAR(255)           NOT NULL,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS role
(
    ID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS emp_user_role
(
    ID            BIGINT AUTO_INCREMENT NOT NULL,
    emp_user_id  BIGINT NOT NULL,
    emp_role_id    BIGINT    NOT NULL,
    PRIMARY KEY (ID)
);
CREATE SEQUENCE seq_post START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE user_seq START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE emp_user_role_seq START WITH 2 INCREMENT BY 1;

INSERT INTO role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO role (id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO user (id, first_name,last_name,email,password) VALUES (1, 'Admin','Admin','admin@anshumanbiswal.com','$2a$10$nvifEte6ZaCuklE3TBpTR.BjzU/4yffO3elRhDYBsUeusm6GdSfrm');
INSERT INTO emp_user_role (id, emp_user_id,emp_role_id) VALUES (1, 1,2);
